BIOWDL-390: Setup PacBio subreads processing pipeline.
biowdl/PacBio-subreads-processing pull request #1
Opened 2020-03-25 10:00 UTC by JasperBoom

2020-05-01 10:08 UTC, JasperBoom commented
I have kept in the "samplesheet" input json for now. It allows me to make sure that the correct barcode fasta file is linked to its associated subreads input bam file.

2020-05-01 13:09 UTC, DavyCats requested changes

2020-05-01 13:09 UTC, DavyCats commented on PacBio-subreads-processing.wdl
> +import "tasks/isoseq3.wdl" as isoseq3
```suggestion
import "tasks/ccs.wdl" as ccs
import "tasks/common.wdl" as common
import "tasks/isoseq3.wdl" as isoseq3
import "tasks/lima.wdl" as lima
```

2020-05-01 13:09 UTC, DavyCats commented on docs/index.md
> +"barcodes_file": "path/to/barcodes.fasta"}]}
```suggestion
{
  "subreads": [
    {
      "subreads_id": "id",
      "subreads_file": "path/to/subreads.bam",
      "subreads_md5": "94127ced6d8428301376ee4ac18df58a",
      "barcodes_file": "path/to/barcodes.fasta"
    }, {
      "subreads_id": "id2",
      "subreads_file": "path/to/subreads2.bam",
      "subreads_md5": "94127ced6d8428301376ee4ac18df58b",
      "barcodes_file": "path/to/barcodes2.fasta"
    }
  ]
}
```

2020-05-01 13:09 UTC, DavyCats commented on docs/index.md
> +<a href='https://github.com/biowdl/sequence-classification/issues'>github issue tracker</a>
Incorrect link

2020-05-06 07:33 UTC, DavyCats approved these changes

2020-05-06 09:00 UTC, merged