Add sample names to workflow output
biowdl/PacBio-subreads-processing pull request #8
Opened 2020-06-17 07:06 UTC by Redmar-van-den-Berg

The sample names are determined by the content of the barcodes fasta
file, which is not accessible for the workflow. This change extracts the
sample names from the lima output files, and adds them to the output as
an array of strings. This way, workflows that incorporate
PacBio-subreads-processing can access the sample names directly

### Checklist
- [x] Pull request details were added to CHANGELOG.md.
- [x] Documentation was updated (if required).
- [x] Workflow `parameter_meta` was added/updated (if required).

2020-06-17 07:11 UTC, rhpvorderman approved these changes

2020-06-17 09:48 UTC, JasperBoom requested changes
Just some nitpicking.

2020-06-17 09:48 UTC, JasperBoom commented on PacBio-subreads-processing.wdl
> +            # fasta file, which is not accessible from the WDL
```suggestion
            # fasta file, which is not accessible from the WDL.
```

2020-06-17 09:48 UTC, JasperBoom commented on PacBio-subreads-processing.wdl
> +
```suggestion
```

2020-06-18 06:28 UTC, JasperBoom approved these changes

2020-06-18 06:28 UTC, merged